server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservationProcessings/** /vehicleinformations/**
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveryProcessings/** 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payProcessings/** 
        - id: customer
          uri: http://localhost:8084
          predicates:
            - Path= /vehicleinformations/**
        - id: carstore
          uri: http://localhost:8085
          predicates:
            - Path=/carProcessings/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservationProcessings/** /vehicleinformations/**
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveryProcessings/** 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payProcessings/** 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path= /vehicleinformations/**
        - id: carstore
          uri: http://carstore:8080
          predicates:
            - Path=/carProcessings/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
